"""Remove last check

Revision ID: 2b8cb5d4d43b
Revises: 493425b4e20a
Create Date: 2020-06-04 21:39:43.982033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b8cb5d4d43b"
down_revision = "493425b4e20a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Subreddit", schema=None) as batch_op:
        batch_op.drop_column("last_check")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Subreddit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_check", sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
