"""Add a last check for subreddits

Revision ID: 493425b4e20a
Revises: 7d97eb4bbe8a
Create Date: 2020-06-04 20:29:44.370443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "493425b4e20a"
down_revision = "7d97eb4bbe8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Subreddit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_check", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Subreddit", schema=None) as batch_op:
        batch_op.drop_column("last_check")

    # ### end Alembic commands ###
