"""init migration

Revision ID: 7d97eb4bbe8a
Revises: 
Create Date: 2020-05-23 20:51:38.952906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d97eb4bbe8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "KVStore",
        sa.Column("key", sa.String(length=15), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_KVStore")),
    )
    op.create_table(
        "Subreddit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("post", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Subreddit")),
        sa.UniqueConstraint("name", name=op.f("uq_Subreddit_name")),
    )
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_User")),
        sa.UniqueConstraint("username", name=op.f("uq_User_username")),
    )
    op.create_table(
        "Subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subreddit_id", sa.Integer(), nullable=False),
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["User.id"], name=op.f("fk_Subscription_author_id_User")
        ),
        sa.ForeignKeyConstraint(
            ["subreddit_id"],
            ["Subreddit.id"],
            name=op.f("fk_Subscription_subreddit_id_Subreddit"),
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["User.id"],
            name=op.f("fk_Subscription_subscriber_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Subscription")),
        sa.UniqueConstraint(
            "subreddit_id",
            "subscriber_id",
            "author_id",
            name=op.f("uq_Subscription_subreddit_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Subscription")
    op.drop_table("User")
    op.drop_table("Subreddit")
    op.drop_table("KVStore")
    # ### end Alembic commands ###
